/**
 * @fileoverview All shared TypeScript interfaces for StadiumIQ.
 * These types are used across components, hooks, services, and utilities.
 */

// ── User & Auth ──────────────────────────────────────────────────────────────

/** Firebase Auth user role — determines access to staff-only routes */
export type UserRole = 'fan' | 'staff' | 'volunteer' | 'admin';

/** Authenticated user profile stored in Firestore */
export interface UserProfile {
  uid: string;
  email: string;
  displayName: string;
  role: UserRole;
  preferredLanguage: SupportedLanguage;
  createdAt: number;
}

// ── i18n ─────────────────────────────────────────────────────────────────────

/** All 8 supported language codes */
export type SupportedLanguage = 'en' | 'es' | 'fr' | 'ar' | 'pt' | 'zh' | 'hi' | 'ja';

// ── Gemini / AI ──────────────────────────────────────────────────────────────

/** A single message in a Gemini chat conversation */
export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: number;
  isOfflineFallback?: boolean;
}

/** Context passed to Gemini for context-aware responses */
export interface GameDayContext {
  currentMatch?: MatchInfo;
  stadiumName?: string;
  userRole?: UserRole;
  currentRoute?: string;
}

/** FIFA World Cup 2026 match information */
export interface MatchInfo {
  id: string;
  homeTeam: string;
  awayTeam: string;
  venue: string;
  city: string;
  kickoffTime: string;
  score?: string;
  status: 'upcoming' | 'live' | 'finished';
}

/** Gemini structured output for crowd prediction */
export interface CrowdPrediction {
  zoneId: string;
  zoneName: string;
  density: 'low' | 'medium' | 'high' | 'critical';
  estimatedCount: number;
  chokePoints: string[];
  recommendation: string;
  confidence: number;
}

/** Rate limiter token bucket state */
export interface TokenBucketState {
  tokens: number;
  lastRefill: number;
}

// ── Fan Hub ──────────────────────────────────────────────────────────────────

/** A food stall in the stadium */
export interface FoodStall {
  id: string;
  name: string;
  section: string;
  gate: string;
  queueLength: 'short' | 'medium' | 'long';
  waitMinutes: number;
  menuItems: string[];
  isOpen: boolean;
  coordinates: GeoPoint;
}

/** Seat location data */
export interface SeatInfo {
  section: string;
  row: string;
  seat: string;
  gate: string;
  directions: string[];
}

// ── Crowd Management ─────────────────────────────────────────────────────────

/** Real-time crowd zone data from Firestore */
export interface CrowdZone {
  id: string;
  name: string;
  capacity: number;
  currentCount: number;
  density: number; // 0–1 float
  alertLevel: AlertLevel;
  lastUpdated: number;
  coordinates: GeoPoint;
}

/** Alert severity levels */
export type AlertLevel = 'green' | 'amber' | 'red';

/** PA announcement generated by Gemini */
export interface PAnnouncement {
  id: string;
  message: string;
  zone: string;
  severity: AlertLevel;
  generatedAt: number;
  approved: boolean;
}

// ── Accessibility ────────────────────────────────────────────────────────────

/** Wheelchair-accessible route */
export interface AccessibleRoute {
  id: string;
  from: string;
  to: string;
  steps: RouteStep[];
  estimatedMinutes: number;
  elevatorRequired: boolean;
  elevatorStatus: 'operational' | 'maintenance' | 'out-of-order';
}

/** A single step in a navigation route */
export interface RouteStep {
  instruction: string;
  distanceMeters: number;
  landmark?: string;
}

/** Assistance request submitted by a fan */
export interface AssistanceRequest {
  id: string;
  userId: string;
  location: string;
  needType: 'mobility' | 'visual' | 'hearing' | 'medical' | 'other';
  notes: string;
  status: 'pending' | 'responding' | 'resolved';
  createdAt: number;
  staffId?: string;
}

/** Elevator status in the stadium */
export interface ElevatorStatus {
  id: string;
  location: string;
  status: 'operational' | 'maintenance' | 'out-of-order';
  lastChecked: number;
}

// ── Transport ────────────────────────────────────────────────────────────────

/** Shuttle route with real-time ETA */
export interface ShuttleRoute {
  id: string;
  name: string;
  from: string;
  to: string;
  etaMinutes: number;
  nextDeparture: string;
  capacity: number;
  occupancy: number;
  isRunning: boolean;
}

/** Parking lot status */
export interface ParkingLot {
  id: string;
  name: string;
  totalSpaces: number;
  availableSpaces: number;
  distanceToGateMeters: number;
  isOpen: boolean;
}

/** Departure wave recommendation */
export interface DepartureWave {
  wave: 1 | 2 | 3;
  recommendedTimeAfterFinalWhistle: string;
  exitGate: string;
  estimatedWaitMinutes: number;
  transportOptions: string[];
}

// ── Sustainability ────────────────────────────────────────────────────────────

/** Per-fan carbon footprint breakdown */
export interface CarbonFootprint {
  travelKgCO2: number;
  foodKgCO2: number;
  totalKgCO2: number;
  equivalentKm: number; // km by car equivalent
  offsetOptions: string[];
}

/** Stadium-wide real-time energy usage */
export interface EnergyUsage {
  currentKw: number;
  peakKw: number;
  renewablePercent: number;
  lastUpdated: number;
}

/** Waste diversion leaderboard entry */
export interface WasteLeaderboardEntry {
  section: string;
  recycledKg: number;
  compostedKg: number;
  landfillKg: number;
  diversionRate: number; // 0–1 float
}

// ── Operations ────────────────────────────────────────────────────────────────

/** Incident report created by staff */
export interface IncidentReport {
  id: string;
  type: 'medical' | 'security' | 'crowd' | 'technical' | 'other';
  location: string;
  description: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'in-progress' | 'resolved';
  reportedBy: string;
  assignedTo?: string;
  createdAt: number;
  updatedAt: number;
}

/** Volunteer / staff resource allocation */
export interface ResourceAllocation {
  id: string;
  zone: string;
  roleType: string;
  volunteersAssigned: number;
  volunteersNeeded: number;
  shift: string;
}

/** Shift schedule entry */
export interface ShiftEntry {
  id: string;
  staffId: string;
  staffName: string;
  role: string;
  zone: string;
  startTime: string;
  endTime: string;
  date: string;
}

// ── Utilities ─────────────────────────────────────────────────────────────────

/** Geographic coordinate */
export interface GeoPoint {
  lat: number;
  lng: number;
}

/** Generic API error */
export interface AppError {
  code: string;
  message: string;
  details?: string;
}

/** Carbon footprint inputs from user */
export interface CarbonInputs {
  transportMode: 'car' | 'bus' | 'metro' | 'walk' | 'bike' | 'flight';
  distanceKm: number;
  mealType: 'meat' | 'vegetarian' | 'vegan';
  numberOfMeals: number;
}
